defmodule JumpstartAi.Repo.Migrations.RemoveHeadersColumn do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:emails) do
      remove :headers
    end
  end

  def down do
    alter table(:emails) do
      add :headers, :map, default: %{}
    end
  end
end
