defmodule JumpstartAi.Repo.Migrations.UpdateContactNotesSchema do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    # First add nullable columns
    alter table(:contact_notes) do
      add :source, :text
      add :external_id, :text
      add :external_created_at, :utc_datetime_usec
      add :external_updated_at, :utc_datetime_usec
    end

    # Update existing contact notes to have source and external_id
    execute """
    UPDATE contact_notes 
    SET source = 'hubspot', 
        external_id = hubspot_note_id,
        external_created_at = hubspot_created_at,
        external_updated_at = hubspot_updated_at
    WHERE hubspot_note_id IS NOT NULL
    """

    # Make the columns not null
    alter table(:contact_notes) do
      modify :source, :text, null: false
      modify :external_id, :text, null: false
    end

    # Remove old columns
    alter table(:contact_notes) do
      remove :hubspot_updated_at
      remove :hubspot_created_at
      remove :hubspot_note_id
    end

    drop_if_exists unique_index(:contact_notes, [:contact_id, :hubspot_note_id],
                     name: "contact_notes_unique_hubspot_note_index"
                   )

    create unique_index(:contact_notes, [:contact_id, :source, :external_id],
             name: "contact_notes_unique_external_note_index"
           )
  end

  def down do
    drop_if_exists unique_index(:contact_notes, [:contact_id, :source, :external_id],
                     name: "contact_notes_unique_external_note_index"
                   )

    # Add back old columns
    alter table(:contact_notes) do
      add :hubspot_note_id, :text
      add :hubspot_created_at, :utc_datetime_usec
      add :hubspot_updated_at, :utc_datetime_usec
    end

    # Migrate data back for hubspot notes
    execute """
    UPDATE contact_notes 
    SET hubspot_note_id = external_id,
        hubspot_created_at = external_created_at,
        hubspot_updated_at = external_updated_at
    WHERE source = 'hubspot'
    """

    create unique_index(:contact_notes, [:contact_id, :hubspot_note_id],
             name: "contact_notes_unique_hubspot_note_index"
           )

    alter table(:contact_notes) do
      remove :external_updated_at
      remove :external_created_at
      remove :external_id
      remove :source
    end
  end
end
