defmodule JumpstartAi.Repo.Migrations.UpdateContactsSchema do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      add :contact_sync_status, :text
      add :contacts_synced_at, :utc_datetime_usec
    end

    # First add nullable columns
    alter table(:contacts) do
      add :source, :text
      add :external_id, :text
      add :external_created_at, :utc_datetime_usec
      add :external_updated_at, :utc_datetime_usec
    end

    # Update existing contacts to have source and external_id
    execute """
    UPDATE contacts 
    SET source = 'hubspot', 
        external_id = hubspot_id,
        external_created_at = hubspot_created_at,
        external_updated_at = hubspot_updated_at
    WHERE hubspot_id IS NOT NULL
    """

    # Make the columns not null
    alter table(:contacts) do
      modify :source, :text, null: false
      modify :external_id, :text, null: false
    end

    # Remove old columns
    alter table(:contacts) do
      remove :hubspot_updated_at
      remove :hubspot_created_at
      remove :hubspot_id
    end

    drop_if_exists unique_index(:contacts, [:user_id, :hubspot_id],
                     name: "contacts_unique_hubspot_contact_index"
                   )

    create unique_index(:contacts, [:user_id, :source, :external_id],
             name: "contacts_unique_external_contact_index"
           )
  end

  def down do
    drop_if_exists unique_index(:contacts, [:user_id, :source, :external_id],
                     name: "contacts_unique_external_contact_index"
                   )

    # Add back old columns
    alter table(:contacts) do
      add :hubspot_id, :text
      add :hubspot_created_at, :utc_datetime_usec
      add :hubspot_updated_at, :utc_datetime_usec
    end

    # Migrate data back for hubspot contacts
    execute """
    UPDATE contacts 
    SET hubspot_id = external_id,
        hubspot_created_at = external_created_at,
        hubspot_updated_at = external_updated_at
    WHERE source = 'hubspot'
    """

    # Make hubspot_id not null
    alter table(:contacts) do
      modify :hubspot_id, :text, null: false
    end

    create unique_index(:contacts, [:user_id, :hubspot_id],
             name: "contacts_unique_hubspot_contact_index"
           )

    alter table(:contacts) do
      remove :external_updated_at
      remove :external_created_at
      remove :external_id
      remove :source
    end

    alter table(:users) do
      remove :contacts_synced_at
      remove :contact_sync_status
    end
  end
end
