defmodule JumpstartAi.Repo.Migrations.AddHubspotTokensToUsers do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      add :hubspot_access_token, :text
      add :hubspot_refresh_token, :text
      add :hubspot_token_expires_at, :utc_datetime_usec
      add :hubspot_portal_id, :text
    end
  end

  def down do
    alter table(:users) do
      remove :hubspot_portal_id
      remove :hubspot_token_expires_at
      remove :hubspot_refresh_token
      remove :hubspot_access_token
    end
  end
end
