defmodule JumpstartAi.Repo.Migrations.AddVectorColumnsToResources do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:contacts) do
      add :full_text_vector, :vector, size: 1536
    end

    alter table(:contact_notes) do
      add :full_text_vector, :vector, size: 1536
    end

    alter table(:calendar_events) do
      add :full_text_vector, :vector, size: 1536
    end
  end

  def down do
    alter table(:calendar_events) do
      remove :full_text_vector
    end

    alter table(:contact_notes) do
      remove :full_text_vector
    end

    alter table(:contacts) do
      remove :full_text_vector
    end
  end
end
