defmodule JumpstartAi.Repo.Migrations.AddMarkdownContentToEmails do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:emails) do
      add :markdown_content, :text
    end
  end

  def down do
    alter table(:emails) do
      remove :markdown_content
    end
  end
end
