defmodule JumpstartAi.Repo.Migrations.AddEmailMetadataFields do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      remove :hashed_password
    end

    alter table(:emails) do
      add :headers, :map, default: %{}
      add :attachments, {:array, :map}, default: []
      add :mime_type, :text
    end
  end

  def down do
    alter table(:emails) do
      remove :mime_type
      remove :attachments
      remove :headers
    end

    alter table(:users) do
      add :hashed_password, :text
    end
  end
end
