defmodule JumpstartAi.Repo.Migrations.AddMentionsToMessages do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:messages) do
      add :mentions, {:array, :map}, default: []
    end
  end

  def down do
    alter table(:messages) do
      remove :mentions
    end
  end
end
