defmodule JumpstartAi.Repo.Migrations.RemoveSyncStatusFields do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      remove :calendar_sync_status
      remove :contact_sync_status
      remove :email_sync_status
    end
  end

  def down do
    alter table(:users) do
      add :email_sync_status, :text
      add :contact_sync_status, :text
      add :calendar_sync_status, :text
    end
  end
end
